apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hostname-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostname
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hostname
        version: v1
      annotations:
              k8s.v1.cni.cncf.io/networks: sriov-stream-net,sriov-storage-net
    spec:
      containers:
      - image: rstarmer/hostname:v1
        imagePullPolicy: Always
        name: hostname
        resources:
          requests:
            intel.com/sriov_stream: '1'
            intel.com/sriov_storage: '1'
          limits:
            intel.com/sriov_stream: '1'
            intel.com/sriov_storage: '1'
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hostname
  name: hostname
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31575
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hostname
  sessionAffinity: None
  type: NodePort

